"""Hash-containment guard for the ritual switch-on (brief 11 §10.8).

The switch-on deliberately touches ZERO lines of `config.py`, so
`research.hashing.config_hash()` -- which hashes every uppercase name in
`config.py` -- must be unchanged by it. This test is blocker B8's standing
guard: any future capture-tag work that adds, renames or removes a config
entry fails here first, in a test whose name says why.

`INTRADAY_CAPTURE_TIMES` is asserted as a KEY SET, not a count, so a rename is
caught as loudly as an addition. It has FIVE keys; the 15:45 `preclose` key is
the one the entire Schwab capture lane runs on.
"""

from __future__ import annotations

import unittest

import config

FROZEN_CONFIG_UPPERCASE_NAMES = (
    "ASSIGNMENT_WATCH_PCT", "ATTRACTIVENESS_EXTRA_NAMES", "ATTRACTIVENESS_UNIVERSE",
    "A_CLOSE_AT_DTE", "A_ENTRY_CREDIT_TOLERANCE", "A_LADDER_BUCKETS",
    "A_PROFIT_TARGET", "A_SHORT_PUT_DELTA", "A_SPREAD_WIDTH",
    "A_SPREAD_WIDTH_SWEEP", "A_STOP_LOSS", "A_TARGET_DTE", "BACKTEST_END",
    "BACKTEST_ENTRY_DATE_SEMANTICS", "BACKTEST_EXECUTION_CONVENTION",
    "BACKTEST_START", "BACKTEST_TERMINAL_EXIT_CONVENTION",
    "BOOTSTRAP_BLOCK_CONSTANTS", "BOOTSTRAP_BLOCK_EXPONENT", "BOOTSTRAP_SAMPLES",
    "BS_DELTA_EPS", "BS_DIVIDEND_INPUT_PATH", "BS_DIVIDEND_STALENESS_RULE",
    "BS_DIVIDEND_UNITS", "BS_IV_EXTREME_HIGH", "BS_IV_EXTREME_LOW", "BS_NOARB_TOL",
    "BS_RATE_STALENESS_RULE", "BS_TREASURY_CURVE_PATH", "BS_TREASURY_SOURCE_URL",
    "BS_TREASURY_UNITS", "CARD3_CLOSE_AT_DTE", "CARD3_DD_LOOKBACK_D",
    "CARD3_DD_MIN", "CARD3_DELTA_BAND", "CARD3_DTE_BAND", "CARD3_MAX_OPEN_PER_NAME",
    "CARD3_NEAR_LOW_LOOKBACK_D", "CARD3_NEAR_LOW_PCT", "CARD3_NEW_LOW_LOOKBACK_D",
    "CARD3_START", "CARD3_TP_MULT", "CHAIN_STALE_BLOCK_SESSIONS",
    "CHAIN_STALE_WARN_SESSIONS", "COHORT_GRANULARITY", "COMMISSION_PER_CONTRACT",
    "COMPOSITE_CHEAP_PCTL", "COMPOSITE_EMA_MEDIUM", "COMPOSITE_EMA_SLOW",
    "COMPOSITE_GRADE_A_MIN_ALIGNED", "COMPOSITE_GRADE_B_MIN_ALIGNED",
    "COMPOSITE_PCTL_MIN_OBS", "COMPOSITE_PCTL_WINDOW", "COMPOSITE_RICH_PCTL",
    "COMPOSITE_SKEW_DELTA", "COMPOSITE_TERM_FAR_DTE", "COMPOSITE_TERM_NEAR_DTE",
    "COMPOSITE_TSMOM_LOOKBACK", "COMPOSITE_TSMOM_SKIP",
    "CONSISTENCY_DELTA_JUMP_ABS", "CONSISTENCY_MAX_EXAMPLES",
    "CONSISTENCY_SPREAD_BLOWOUT_MIN_RATIO", "CONSISTENCY_UNDERLYING_SMALL_MOVE",
    "CONTEXT_LANE_ENABLED",
    "CSCV_MIN_SPLITS_S",
    "CSCV_MIN_VARIANTS_M", "DSR_DEFAULT_MEAN_TRIAL_SR", "DSR_MIN_N_TRIALS",
    "DSR_MIN_T", "DTE_MIN", "EARNINGS_COVERAGE_DAYS", "EXPERIMENTS_OUTPUT_PATH",
    "EXP_BETA_HALF_WINDOW", "EXP_BETA_MIN_OBS", "EXP_BETA_UNSTABLE_DELTA",
    "EXP_BETA_WINDOW", "EXP_SPREAD_BASELINE", "EXP_SPREAD_ELEVATED",
    "EXP_SPREAD_LOOKBACK_SESSIONS", "EXP_SPREAD_MIN_BASELINE_OBS",
    "EXP_SPREAD_TARGET_DELTA", "EXP_SPREAD_TENOR_DTE", "EXP_TAIL_ALT_WINDOWS",
    "EXP_TAIL_JUMP_SIGMA", "EXP_TAIL_MIN_OBS", "EXP_TAIL_WINDOW",
    "EXP_TBILL_TARGET_DELTA", "EXP_TBILL_TENOR_DTE", "FEED_CALL_DELTA_BAND",
    "FEED_PUT_DELTA_BAND", "FILL_MODEL_ID", "H10A_WINDOW_END", "H10B_RESUME_FLOOR_SESSION",
    "H10B_WINDOW_END",
    "H10_DELTA_MAX", "H10_DELTA_MIN", "H10_DTE_EXIT", "H10_DTE_MAX", "H10_DTE_MIN",
    "H10_MAX_PREMIUM_PER_TRADE", "H10_MIN_LOSSES_FOR_VERDICT",
    "H10_MONTHLY_PREMIUM_CAP", "H10_PROFIT_TARGET_PCT", "H10_STRIKE_BAND_PCT",
    "H10_TIME_EXIT_SESSIONS", "H4_CSP_DELTA", "H4_CSP_MAX_POSITIONS",
    "H4_CSP_NAMES", "H4_TACTICAL_DELTA", "H4_TACTICAL_MAX_OPEN", "H4_THESIS_DELTA",
    "H4_THESIS_DTE_BAND", "H4_THESIS_MAX_POSITIONS",
    "H4_THESIS_MAX_PREMIUM_PER_NAME", "H4_THESIS_MAX_PREMIUM_TOTAL",
    "H4_THESIS_NAMES", "H4_THESIS_ROLL_DTE", "H5_CC_UPSIDE_GREEN",
    "H5_CC_YIELD_AMBER", "H5_CC_YIELD_GREEN", "H5_CUSHION_AMBER",
    "H5_CUSHION_GREEN", "H5_ENTRY_IVR_MAX", "H5_ENTRY_TRIGGERS", "H5_INCOME_DELTA",
    "H5_INCOME_DELTA_BAND", "H5_IVR_BUY_GREEN", "H5_IVR_BUY_RED",
    "H5_IVR_SELL_GREEN", "H5_PUT_YIELD_AMBER", "H5_PUT_YIELD_GREEN",
    "H5_RESUME_FLOOR_SESSION", "H5_VRP_SELL_GREEN", "H6_CLOSE_AT_DTE", "H6_DELTA_BAND", "H6_DTE_BAND",
    "H6_EARNINGS_BAN_SESSIONS", "H6_HARD_KILL_FULL_LOSS_MONTHS", "H6_IVR_MAX",
    "H6_KILL_V2_EFFECTIVE_ENTRY_DATE", "H6_KILL_V2_TRIAL_INTENT_HASH",
    "H6_MAX_ASK_DOLLARS", "H6_MAX_CONCURRENT", "H6_MAX_CONTRACTS_PER_NAME",
    "H6_MIN_COMPLETED_POSITIONS", "H6_MONTHLY_PREMIUM_AT_RISK", "H6_NAMES",
    "H6_POST_EARNINGS_SESSIONS", "H6_TAKE_PROFIT_PCT", "H7A_DRAWDOWN_MIN",
    "H7A_RECLAIM_LOOKBACK_D", "H7B_RANGE_LOOKBACK_D", "H7B_RANGE_MAX",
    "H7B_RV_HISTORY_D", "H7B_RV_MIN_HISTORY_D", "H7B_RV_PCTILE_MAX",
    "H7B_RV_WINDOW_D", "H7C_CLOSE_AT_DTE", "H7C_CLOSE_BEFORE_EARNINGS",
    "H7C_CREDIT_FLOOR_FRAC", "H7C_DTE_BAND", "H7C_MAX_CONCURRENT",
    "H7C_SHORT_DELTA_MAX", "H7C_STOP_CREDIT_MULT", "H7C_TIEBREAK", "H7C_TP_FRAC",
    "H7C_WIDTH_FRAC_OF_SPOT", "H7_ADMIT_MAX_SPREAD_PCT", "H7_ADMIT_MIN_CONTRACTS",
    "H7_BACKTEST_END", "H7_BACKTEST_START", "H7_BACKTEST_SYMBOLS",
    "H7_CLOSES_LOOKBACK_D", "H7_CLOSE_AT_DTE", "H7_CORE_LONG_ONLY",
    "H7_DD_LOOKBACK_D", "H7_DELTA_TOLERANCE", "H7_DIAGNOSTIC_CONTRACTS",
    "H7_EARNINGS_BAN_SESSIONS", "H7_EARNINGS_ESTIMATE_CLUSTER_D",
    "H7_EARNINGS_POST_REPORT_GRACE_D", "H7_EXCLUDED", "H7_FORWARD_CONTRACTS",
    "H7_HISTORICAL_WITHDRAWAL_HASH", "H7_IV_CHEAP_K", "H7_IV_PAR_K", "H7_IV_RICH_K",
    "H7_IV_TENOR_DTE_BAND", "H7_LANE_PRIORITY", "H7_LONG_DELTA_BAND",
    "H7_LONG_DTE_BAND", "H7_LONG_TP_PCT", "H7_MAX_HOLD_BUFFER_D",
    "H7_MAX_OPEN_PER_UNDERLYING", "H7_MONTHLY_AT_RISK", "H7_NTM_BAND",
    "H7_POST_REPORT_GRACE_DAYS", "H7_RV_LOOKBACK_D", "H7_SIGNAL_CLOSES_START",
    "H7_SOURCE_HEALTH_WARN_SESSIONS", "H7_SPREAD_LONG_DELTA",
    "H7_SPREAD_SHORT_DELTA", "H7_SPREAD_TP_FRAC_MAX", "H7_WARMUP_EXTRA_SESSIONS",
    "H7_WATCHLIST", "H8_CAP_SHARED_WITH_H6", "H8_DELTA_BAND", "H8_DTE_BAND",
    "H8_ENTRY_WINDOW_SESSIONS", "H8_EXIT_SESSIONS_BEFORE_REPORT",
    "H8_HARD_KILL_FULL_LOSS_MONTHS", "H8_IVR_MAX", "H8_MAX_ASK_DOLLARS",
    "H8_MAX_CONCURRENT", "H8_MAX_CONTRACTS_PER_NAME", "H8_MIN_COMPLETED_POSITIONS",
    "H8_NAMES", "H8_TAKE_PROFIT_PCT", "H9_MAX_UNRESOLVED_GAP_FRACTION",
    "H9_MIN_ELIGIBLE_EVENTS", "H9_NAMES", "H9_NEXT_REPORT_EXIT_SESSIONS",
    "H9_PREMIUM_CAP_DOLLARS", "H9_REACTION_MIN", "H9_SECONDARY_COHORT",
    "H9_SPEC_PATH", "H9_WINDOW", "HALF_SPREAD_COST", "INTRADAY_CACHE_DIR",
    "INTRADAY_CAPTURE_TIMES", "INTRADAY_CAPTURE_TOLERANCE_MINUTES",
    "INTRADAY_RECEIPT_DIR", "IN_SAMPLE_END", "IV_CALIBRATION_IQR_MAX",
    "IV_CALIBRATION_MAX_AGE_DAYS", "IV_CALIBRATION_MEDIAN_ABS_DIFF_MAX",
    "IV_CALIBRATION_RECEIPT_DIR", "IV_CALIBRATION_SESSIONS",
    "LIVE_CACHE_TTL_SECONDS", "LIVE_DASH_PORT", "LIVE_POLL_SECONDS",
    "LIVE_PROBE_MAX_AGE_DAYS", "LIVE_QUOTE_MAX_AGE_SECONDS", "MAX_LOSS_PER_TRADE",
    "MAX_SPREAD_PCT", "MIN_LOSSES_FOR_VERDICT", "MIN_OPEN_INTEREST",
    "OI_CHANGE_MAX_PRIOR_GAP_DAYS", "OI_CHANGE_MIN_BASE", "OI_CHANGE_NOTABLE_PCTL",
    "OI_CHANGE_PCTL_WINDOW", "OI_CHANGE_PCT_MIN_OBS", "OOS_LOOK_BUDGET",
    "PICK_GREEN_POINT", "PICK_PINNED_SYMBOLS", "PICK_RANK_LEADER_BONUS",
    "PICK_TECH_BONUS", "PICK_TOP_N", "QM_BASE_MAX_DAYS", "QM_BASE_MAX_DEPTH",
    "QM_BASE_MIN_DAYS",
    "QM_BASE_SMA", "QM_HORIZONS", "QM_NTM_BAND", "QM_PARA_EXT_PCT",
    "QM_PARA_GREEN_DAYS", "QM_PARA_LOOKBACK", "QM_PARA_MIN_PCT", "QM_PARA_SMA",
    "QM_RUN_LOOKBACK", "QM_RUN_MIN_PCT", "QM_TRADABILITY_DTE", "QM_VOL_DRYUP_RATIO",
    "REGIME_MIN_FIT_WINDOWS", "REGIME_N_CLUSTERS", "REGIME_N_INIT",
    "REGIME_REFIT_EVERY", "REGIME_SEED", "REGIME_STEP_DAYS", "REGIME_SYMBOLS",
    "REGIME_WINDOW_DAYS", "RISK_SLEEVE", "RQ1_CACHE_START", "RQ1_HORIZON_SESSIONS",
    "RQ1_NOTABLE_ABS_RHO", "RQ1_RV_ANNUALIZATION_SESSIONS", "SHORT_CONTEXT_ENABLED",
    "SHORT_POSITIONING_MAX_AGE_RELEASES", "SHORT_POSITIONING_PROVIDER_ORDER",
    "SHORT_POSITIONING_ROOT", "SLIPPAGE_HAIRCUT", "STARTING_CAPITAL",
    "STUDY_ERA_START", "TECH_52W_LOOKBACK", "TECH_BREAKOUT_LOOKBACK", "TECH_MOM_1M",
    "TECH_MOM_3M", "TECH_SMA_WINDOWS", "UNIVERSE",
)

FROZEN_INTRADAY_CAPTURE_KEYS = frozenset(
    {"open_auction", "open", "midmorning", "midday", "preclose"}
)


class ConfigHashSurfaceTests(unittest.TestCase):
    def test_config_hash_surface_unchanged(self):
        """Guards the NAME SET only, per spec §10.8.

        `config_hash()` hashes each name's VALUE too; this test deliberately
        freezes only the set of uppercase names, so an owner-typed change to an
        existing constant's value is NOT caught here (it is a registered-number
        change with its own discipline). What is caught is any ADDITION,
        REMOVAL or RENAME of a config entry -- the blast radius this brief's
        "config.py: zero lines" claim depends on.
        """
        names = tuple(
            sorted(
                name
                for name in vars(config)
                if name[:1].isalpha() and name.upper() == name
            )
        )
        self.assertEqual(names, FROZEN_CONFIG_UPPERCASE_NAMES)

    def test_intraday_capture_times_has_exactly_its_five_keys(self):
        self.assertEqual(
            frozenset(config.INTRADAY_CAPTURE_TIMES), FROZEN_INTRADAY_CAPTURE_KEYS
        )
        self.assertEqual(len(config.INTRADAY_CAPTURE_TIMES), 5)
        self.assertIn("preclose", config.INTRADAY_CAPTURE_TIMES)


if __name__ == "__main__":
    unittest.main()
